### ISSUE TITLE
ETL Cleanup

### ISSUE THREAD

**Issue by philipstubbs13** [abbylemon/mental_health_ML#10]
* Global update: convert True/False to 1/0. 1 being true, 0 being false.

* Running the `pd.to_numeric` cell in the `cloud_etl.ipynb` notebook is erroring out:

```
ValueError: Unable to parse string "Yes"

During handling of the above exception, another exception occurred:

----> 4 survey_df3['is_tech_company'] = pd.to_numeric(survey_df3['is_tech_company'])
```

Easy fix for the `pd.to_numeric` error is I don't think `pd.to_numeric` is necessary here (?) Can we just remove `pd.to_numeric` from that cell?

* Running `.value_counts` on the `is_tech_company` and `sought_treatment_for_mental_health` columns shows four values: `Yes, No, True, False`. Need to get this down to 2 values (update to be 1/0 for all rows in these columns to match schema).

* `NaN` is still showing up for some columns. This needs to be converted to `None` to be able to load into SQL/Postgres.

* Fix typo in column name in the db documentation, in `cloud_etl.ipynb`, and in `schema.ipynb` :

 `discussiong_physical_has_consequences_previous_employer`

* Bonus Cleanup
  * `number_employees` was changed in the `schema.ipynb` file from Integer to String but the documentation was not updated. Update documentation here: <https://github.com/abbylemon/mental_health_ML/blob/master/docs/database.md>

**Comment by abbylemon** [comment]
All true/false columns are now marked as booleans, and the columns are no longer casted to numeric in the etl file.

I fixed the typo in my last push when editing column types to bool.
